language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '12'
install:
  - yarn global add codecov

jobs:
  include:
    - stage: test
      script: yarn validate
      script: codecov
    - stage: release
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
        on:
          branch: master
