language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
before_install:
  - yarn global add codecov
before_script:
  - yarn validate
  - yarn clean
script: yarn rollup:build:prod
after_success:
  - codecov
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  only:
    - master
