language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '12'
before_install:
  - yarn global add codecov
before_script:
  - yarn validate
script: yarn build
after_success:
  - codecov
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  only:
    - master
    - /^greenkeeper/.*$/
