FORMAT: 1A
HOST: https://github-trending-api.now.sh/

# GitHub Trending API

GitHub Trending API is a simple API to fetch trending repositories and developers.

## Languages Collection [/languages]

### List All Languages [GET]

+ Response 200 (application/json)

        {
            "popular": [
                {
                    "id": "c++",
                    "name": "C++"
                },
                {
                    "id": "html",
                    "name": "HTML"
                },
                {
                    "id": "java",
                    "name": "Java"
                },
                {
                    "id": "javascript",
                    "name": "JavaScript"
                },
                {
                    "id": "php",
                    "name": "PHP"
                },
                {
                    "id": "python",
                    "name": "Python"
                },
                {
                    "id": "ruby",
                    "name": "Ruby"
                }
            ],
            "all": [
                {
                    "id": "1c-enterprise",
                    "name": "1C Enterprise"
                },
                {
                    "id": "abap",
                    "name": "ABAP"
                },
                {
                    "id": "abnf",
                    "name": "ABNF"
                },
                {
                    "id": "actionscript",
                    "name": "ActionScript"
                },
                {
                    "id": "ada",
                    "name": "Ada"
                },
                {
                    "id": "adobe-font-metrics",
                    "name": "Adobe Font Metrics"
                },
                {
                    "id": "agda",
                    "name": "Agda"
                },
                {
                    "id": "ags-script",
                    "name": "AGS Script"
                }
            ]
        }

