FORMAT: 1A
HOST: https://ghapi.huchen.dev/

# GitHub Trending API

GitHub Trending API is a simple API to fetch trending repositories and developers.

## Repositories [/repositories{?language,since,spoken_language_code}]

+ Parameters
    + language (string, optional) - Programming language
    + since (string, optional) - Trending period: `daily`, `weekly`, `monthly`
        + Default: `daily`
    + spoken_language_code (string, optional) - Spoken language

### List Trending Repositories [GET]

+ Response 200 (application/json)

        [
            {
                "author": "xingshaocheng",
                "name": "architect-awesome",
                "avatar": "https://github.com/xingshaocheng.png",
                "url": "https://github.com/xingshaocheng/architect-awesome",
                "description": "后端架构师技术图谱",
                "language": "Go",
                "languageColor": "#3572A5",
                "stars": 7333,
                "forks": 1546,
                "currentPeriodStars": 1528,
                "builtBy": [
                    {
                        "href": "https://github.com/viatsko",
                        "avatar": "https://avatars0.githubusercontent.com/u/376065",
                        "username": "viatsko"
                    }
                ]
            },
            {
                "author": "google",
                "name": "gvisor",
                "avatar": "https://github.com/google.png",
                "url": "https://github.com/google/gvisor",
                "description": "Container Runtime Sandbox",
                "language": "Go",
                "languageColor": "#3572A5",
                "stars": 3346,
                "forks": 118,
                "currentPeriodStars": 1624,
                "builtBy": [
                    {
                        "href": "https://github.com/viatsko",
                        "avatar": "https://avatars0.githubusercontent.com/u/376065",
                        "username": "viatsko"
                    }
                ]
            },
            {
                "author": "davideuler",
                "name": "architecture.of.internet-product",
                "avatar": "https://github.com/davideuler.png",
                "url": "https://github.com/davideuler/architecture.of.internet-product",
                "description": "互联网公司技术架构，微信/淘宝/腾讯/阿里/美团点评/百度/微博/Google/Facebook/Amazon/eBay的架构，欢迎PR补充",
                "language": "Go",
                "languageColor": "#3572A5",
                "stars": 2763,
                "forks": 416,
                "currentPeriodStars": 1427,
                "builtBy": [
                    {
                        "href": "https://github.com/viatsko",
                        "avatar": "https://avatars0.githubusercontent.com/u/376065",
                        "username": "viatsko"
                    }
                ]
            },
            {
                "author": "kusti8",
                "name": "proton-native",
                "avatar": "https://github.com/kusti8.png",
                "url": "https://github.com/kusti8/proton-native",
                "description": "A React environment for cross platform native desktop apps",
                "language": "JavaScript",
                "languageColor": "#3572A5",
                "stars": 4711,
                "forks": 124,
                "currentPeriodStars": 1186,
                "builtBy": [
                    {
                        "href": "https://github.com/viatsko",
                        "avatar": "https://avatars0.githubusercontent.com/u/376065",
                        "username": "viatsko"
                    }
                ]
            }
        ]

## Developers [/developers{?language,since}]

+ Parameters
    + language (string, optional) - Programming language
    + since (string, optional) - Trending period: `daily`, `weekly`, `monthly`
        + Default: `daily`

### List Trending Developers [GET]

+ Response 200 (application/json)

        [
            {
                "username": "google",
                "name": "Google",
                "type": "organization",
                "url": "https://github.com/google",
                "avatar": "https://avatars0.githubusercontent.com/u/1342004",
                "repo": {
                    "name": "material-design-icons",
                    "description": "Material Design icons by Google",
                    "url": "https://github.com/google/material-design-icons"
                }
            },
            {
                "username": "davideuler",
                "name": "david l euler",
                "type": "user",
                "url": "https://github.com/davideuler",
                "avatar": "https://avatars3.githubusercontent.com/u/377983",
                "repo": {
                    "name": "architecture.of.internet-product",
                    "description":
                        "互联网公司技术架构，微信/淘宝/腾讯/阿里/美团点评/百度/微博/Google/Facebook/Amazon/eBay的架构，欢迎PR补充",
                    "url": "https://github.com/davideuler/architecture.of.internet-product"
                }
            },
            {
                "username": "xingshaocheng",
                "type": "user",
                "url": "https://github.com/xingshaocheng",
                "avatar": "https://avatars1.githubusercontent.com/u/4962837",
                "repo": {
                    "name": "architect-awesome",
                    "description": "后端架构师技术图谱",
                    "url": "https://github.com/xingshaocheng/architect-awesome"
                }
            },
            {
                "username": "cyanharlow",
                "name": "Diana Smith",
                "type": "user",
                "url": "https://github.com/cyanharlow",
                "avatar": "https://avatars2.githubusercontent.com/u/8030961",
                "repo": {
                    "name": "purecss-francine",
                    "description":
                        "HTML/CSS drawing in the style of an 18th-century oil painting. Hand-coded entirely in HTML & CSS.",
                    "url": "https://github.com/cyanharlow/purecss-francine"
                }
            }
        ]

## Languages Collection [/languages]

### List Languages [GET]

+ Response 200 (application/json)

        [
            {
                "id": "1c-enterprise",
                "name": "1C Enterprise"
            },
            {
                "id": "abap",
                "name": "ABAP"
            },
            {
                "id": "abnf",
                "name": "ABNF"
            },
            {
                "id": "actionscript",
                "name": "ActionScript"
            }
        ]

## Spoken Languages Collection [/spoken_languages]

### List Spoken Languages [GET]

+ Response 200 (application/json)

        [
            {
                "urlParam": "ab",
                "name": "Abkhazian"
            },
            {
                "urlParam": "aa",
                "name": "Afar"
            },
            {
                "urlParam": "af",
                "name": "Afrikaans"
            },
            {
                "urlParam": "ak",
                "name": "Akan"
            },
        ]
